[CmdletBinding()]
param(
    [switch]$Check,
    [string]$Output = (Join-Path $PSScriptRoot '..' 'docs' 'cmdlets')
)

$ErrorActionPreference = 'Stop'

$script:Utf8NoBom = [System.Text.UTF8Encoding]::new($false)
$script:Banner = '<!-- Generated by scripts/generate_ps_cmdlet_docs.ps1. Do not edit by hand. -->'
$script:PlatyPsVersion = '1.0.1'

function Get-RepoRelativePath {
    [CmdletBinding()]
    [OutputType([string])]
    param(
        [Parameter(Mandatory)]
        [string]$RepoRoot,

        [Parameter(Mandatory)]
        [string]$Path
    )

    $repoRootWithSlash = [System.IO.Path]::TrimEndingDirectorySeparator($RepoRoot) + [System.IO.Path]::DirectorySeparatorChar
    $uriRoot = [System.Uri]::new($repoRootWithSlash)
    $uriPath = [System.Uri]::new($Path)
    $relative = $uriRoot.MakeRelativeUri($uriPath).ToString()
    return [System.Uri]::UnescapeDataString($relative).Replace('/', '\')
}

function ConvertTo-PortableRelativePath {
    [CmdletBinding()]
    [OutputType([string])]
    param(
        [Parameter(Mandatory)]
        [string]$Path
    )

    return $Path.Replace('\', '/')
}

function ConvertTo-MarkdownContent {
    [CmdletBinding()]
    [OutputType([string])]
    param(
        [Parameter(Mandatory)]
        [string]$Content,

        [switch]$WithBanner
    )

    $normalized = $Content -replace "`r`n", "`n" -replace "`r", "`n"
    $normalized = [regex]::Replace($normalized, '(?m)^ms\.date:\s*.*$', 'ms.date: 01/01/0001')
    $normalized = [regex]::Replace($normalized, '(?m)^Locale:\s*.*$', 'Locale: en-US')
    if ($WithBanner) {
        $normalized = "$script:Banner`n`n$normalized"
    }
    if (-not $normalized.EndsWith("`n", [System.StringComparison]::Ordinal)) {
        $normalized += "`n"
    }
    return $normalized
}

function Write-Utf8NoBomFile {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [string]$Path,

        [Parameter(Mandatory)]
        [string]$Content
    )

    [System.IO.Directory]::CreateDirectory([System.IO.Path]::GetDirectoryName($Path)) | Out-Null
    [System.IO.File]::WriteAllText($Path, $Content, $script:Utf8NoBom)
}

function Get-CmdletReferenceReadme {
    [CmdletBinding()]
    [OutputType([string])]
    param(
        [Parameter(Mandatory)]
        [hashtable]$SynopsisByCmdlet
    )

    $groups = [ordered]@{
        'Core'              = @('Get-FinOpsInfo', 'Invoke-FinOpsAssessment', 'Invoke-FinOpsTriage', 'Test-FinOpsConfiguration')
        'Exporters'         = @('Export-FinOpsFocusAligned', 'Export-FinOpsPlaybook')
        'Live collection'   = @('Invoke-FinOpsLiveCollection')
        'Read-only guards'  = @('Assert-FinOpsReadOnlyScope', 'Test-FinOpsReadOnlyScope')
    }

    $lines = [System.Collections.Generic.List[string]]::new()
    $lines.Add($script:Banner)
    $lines.Add('')
    $lines.Add('# FinOpsAssess cmdlet reference')
    $lines.Add('')
    $lines.Add('Auto-generated from comment-based help using Microsoft.PowerShell.PlatyPS v1.0.1.')
    $lines.Add('Run `pwsh ./scripts/generate_ps_cmdlet_docs.ps1` to regenerate.')
    $lines.Add('')
    $lines.Add('> MAML bundling is intentionally deferred for Phase 7c. Runtime `Get-Help` currently uses comment-based help.')
    $lines.Add('')
    $lines.Add('## Module topics')
    $lines.Add('')
    $lines.Add('- [FinOpsAssess](FinOpsAssess.md)')
    $lines.Add('')

    foreach ($groupName in $groups.Keys) {
        $lines.Add("## $groupName")
        $lines.Add('')
        $lines.Add('| Cmdlet | Synopsis |')
        $lines.Add('|---|---|')
        foreach ($cmdletName in $groups[$groupName]) {
            $synopsis = [string]$SynopsisByCmdlet[$cmdletName]
            $synopsis = ($synopsis -replace '\s+', ' ').Trim()
            $escapedSynopsis = $synopsis.Replace('|', '\|')
            $lines.Add("| [$cmdletName]($cmdletName.md) | $escapedSynopsis |")
        }
        $lines.Add('')
    }

    return ($lines -join "`n") + "`n"
}

function Get-StagedGeneratedFileMap {
    [CmdletBinding()]
    [OutputType([hashtable])]
    param(
        [Parameter(Mandatory)]
        [string]$RepoRoot,

        [Parameter(Mandatory)]
        [string]$OutputPath
    )

    if (-not (Get-Command -Name Install-PSResource -ErrorAction SilentlyContinue)) {
        Install-Module -Name Microsoft.PowerShell.PlatyPS -RequiredVersion $script:PlatyPsVersion -Scope CurrentUser -Force -AllowClobber
    } elseif (-not (Get-Module -ListAvailable Microsoft.PowerShell.PlatyPS | Where-Object { $_.Version -eq [version]$script:PlatyPsVersion })) {
        Install-PSResource -Name Microsoft.PowerShell.PlatyPS -Version $script:PlatyPsVersion -TrustRepository -Scope CurrentUser
    }
    Import-Module Microsoft.PowerShell.PlatyPS -RequiredVersion $script:PlatyPsVersion -Force

    $helpModulePath = Join-Path $RepoRoot 'scripts' 'FinOpsCmdletHelp.psm1'
    Import-Module $helpModulePath -Force

    $manifestPath = Join-Path $RepoRoot 'powershell' 'FinOpsAssess' 'FinOpsAssess.psd1'
    $manifest = Import-PowerShellDataFile -LiteralPath $manifestPath
    $exportedCmdlets = @($manifest.FunctionsToExport | ForEach-Object { [string]$_ })
    if ($exportedCmdlets.Count -eq 0) {
        throw "FunctionsToExport is empty in $manifestPath"
    }

    Import-Module $manifestPath -Force
    Test-FinOpsCmdletHelpCompleteness -Name $exportedCmdlets -ThrowOnFailure

    $stagingRoot = Join-Path ([System.IO.Path]::GetTempPath()) ("finops-cmdlet-docs-" + [guid]::NewGuid().ToString('N'))
    $stagingModuleRoot = Join-Path $stagingRoot 'FinOpsAssess'
    $outputData = @{}
    try {
        [System.IO.Directory]::CreateDirectory($stagingRoot) | Out-Null
        $commandHelp = [System.Collections.Generic.List[object]]::new()
        $previousErrorActionPreference = $ErrorActionPreference
        try {
            $ErrorActionPreference = 'Continue'
            foreach ($cmdletName in $exportedCmdlets) {
                try {
                    $commandHelp.Add((New-CommandHelp -CommandInfo (Get-Command -Name $cmdletName -ErrorAction Stop)))
                } catch {
                    throw "Failed to build markdown help model for ${cmdletName}: $($_.Exception.Message)"
                }
            }
        } finally {
            $ErrorActionPreference = $previousErrorActionPreference
        }
        Export-MarkdownCommandHelp `
            -CommandHelp $commandHelp `
            -OutputFolder $stagingRoot `
            -Encoding $script:Utf8NoBom `
            -Force | Out-Null
        New-MarkdownModuleFile `
            -CommandHelp $commandHelp `
            -OutputFolder $stagingRoot `
            -HelpVersion '0.1.0' `
            -Locale 'en-US' `
            -Force | Out-Null

        $synopsisByCmdlet = @{}
        foreach ($cmdletName in $exportedCmdlets) {
            $synopsisByCmdlet[$cmdletName] = [string](Get-Help -Name $cmdletName -ErrorAction Stop).Synopsis
            $sourcePath = Join-Path $stagingModuleRoot "$cmdletName.md"
            $content = [System.IO.File]::ReadAllText($sourcePath)
            $outputData["$cmdletName.md"] = ConvertTo-MarkdownContent -Content $content -WithBanner
        }

        $modulePagePath = Join-Path $stagingModuleRoot 'FinOpsAssess.md'
        $modulePageContent = [System.IO.File]::ReadAllText($modulePagePath)
        $outputData['FinOpsAssess.md'] = ConvertTo-MarkdownContent -Content $modulePageContent -WithBanner

        $readme = Get-CmdletReferenceReadme -SynopsisByCmdlet $synopsisByCmdlet
        $outputData['README.md'] = ConvertTo-MarkdownContent -Content $readme
    } finally {
        if (Test-Path -LiteralPath $stagingRoot) {
            Remove-Item -LiteralPath $stagingRoot -Recurse -Force
        }
    }

    $expected = [System.Collections.Generic.List[string]]::new()
    foreach ($cmdletName in $exportedCmdlets | Sort-Object) {
        $expected.Add("$cmdletName.md")
    }
    $expected.Add('FinOpsAssess.md')
    $expected.Add('README.md')

    return @{
        Files          = $outputData
        ExpectedNames  = $expected.ToArray()
        TargetPath     = $OutputPath
    }
}

function Test-CmdletDocsDrift {
    [CmdletBinding()]
    [OutputType([bool])]
    param(
        [Parameter(Mandatory)]
        [string]$RepoRoot,

        [Parameter(Mandatory)]
        [hashtable]$Generated
    )

    $stale = [System.Collections.Generic.List[string]]::new()
    $targetPath = $Generated.TargetPath

    foreach ($name in $Generated.ExpectedNames) {
        $targetFile = Join-Path $targetPath $name
        if (-not (Test-Path -LiteralPath $targetFile -PathType Leaf)) {
            $stale.Add((ConvertTo-PortableRelativePath -Path (Get-RepoRelativePath -RepoRoot $RepoRoot -Path $targetFile)))
            continue
        }
        $expectedBytes = $script:Utf8NoBom.GetBytes($Generated.Files[$name])
        $actualBytes = [System.IO.File]::ReadAllBytes($targetFile)
        if (-not [System.Linq.Enumerable]::SequenceEqual($expectedBytes, $actualBytes)) {
            $stale.Add((ConvertTo-PortableRelativePath -Path (Get-RepoRelativePath -RepoRoot $RepoRoot -Path $targetFile)))
        }
    }

    if (Test-Path -LiteralPath $targetPath -PathType Container) {
        $actualNames = @(Get-ChildItem -LiteralPath $targetPath -Filter '*.md' -File | ForEach-Object { $_.Name })
        foreach ($name in ($actualNames | Sort-Object)) {
            if ($name -notin $Generated.ExpectedNames) {
                $targetFile = Join-Path $targetPath $name
                $stale.Add((ConvertTo-PortableRelativePath -Path (Get-RepoRelativePath -RepoRoot $RepoRoot -Path $targetFile)))
            }
        }
    }

    if ($stale.Count -gt 0) {
        foreach ($path in $stale | Sort-Object -Unique) {
            Write-Information "stale: $path" -InformationAction Continue
        }
        return $false
    }

    Write-Information 'ok: cmdlet docs are up-to-date' -InformationAction Continue
    return $true
}

$repoRoot = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$resolvedOutputInput = if ([System.IO.Path]::IsPathRooted($Output)) {
    $Output
} else {
    Join-Path $repoRoot $Output
}
[System.IO.Directory]::CreateDirectory($resolvedOutputInput) | Out-Null
$outputPath = (Resolve-Path -LiteralPath $resolvedOutputInput).Path
$generated = Get-StagedGeneratedFileMap -RepoRoot $repoRoot -OutputPath $outputPath

if ($Check) {
    if (-not (Test-CmdletDocsDrift -RepoRoot $repoRoot -Generated $generated)) {
        exit 1
    }
    exit 0
}

if (Test-Path -LiteralPath $outputPath -PathType Container) {
    Get-ChildItem -LiteralPath $outputPath -Filter '*.md' -File | Remove-Item -Force
}
foreach ($name in ($generated.Files.Keys | Sort-Object)) {
    $target = Join-Path $outputPath $name
    Write-Utf8NoBomFile -Path $target -Content $generated.Files[$name]
    $relativePath = ConvertTo-PortableRelativePath -Path (Get-RepoRelativePath -RepoRoot $repoRoot -Path $target)
    Write-Information "wrote $relativePath" -InformationAction Continue
}
