"""Regenerate `docs/rules.md` and `examples/demo-report.{json,html,csv}`.

Single source of truth for two committed artefacts that would otherwise
drift from the codebase:

* ``docs/rules.md`` — a human-readable reference table of every rule
  shipped under ``data/rules/*.yaml``, annotated with whether the rule
  has a registered Python implementation in
  ``src/finops_assess/rules_impl/``.
* ``examples/demo-report.{json,html,csv}`` — the deterministic output of
  ``finops-assess demo`` against the bundled synthetic tenant, used as a
  preview for prospective users without requiring them to install the
  tool.

Determinism
-----------
Reports are normally timestamped with wall-clock UTC. To make the
committed examples byte-stable across CI machines and contributor
checkouts, this script sets ``SOURCE_DATE_EPOCH=0`` and passes a fixed
salt for principal redaction. The synthetic tenant contains no real PII
so redaction is left enabled — same posture as a real run.

CI freshness gate
-----------------
``.github/workflows/docs.yml`` re-runs this script and fails the build
on any uncommitted diff, so a PR that adds a rule or edits demo data
must regenerate the docs.

Usage
-----
::

    python scripts/generate_docs.py            # write artefacts in-place
    python scripts/generate_docs.py --check    # exit 1 on any diff
"""

from __future__ import annotations

import argparse
import filecmp
import os
import shutil
import sys
import tempfile
from pathlib import Path

from finops_assess.catalog import load_catalog
from finops_assess.collectors import collect_from_directory
from finops_assess.demo import materialise_demo_data
from finops_assess.engine import registered_rule_ids, run_rules
from finops_assess.persona import assign_personas
from finops_assess.reporters import (
    write_csv_report,
    write_html_report,
    write_json_report,
)
from finops_assess.reporters.json_reporter import build_report
from finops_assess.rules import load_personas, load_rules

REPO_ROOT = Path(__file__).resolve().parents[1]
DOCS_RULES_PATH = REPO_ROOT / "docs" / "rules.md"
EXAMPLES_DIR = REPO_ROOT / "examples"
EXAMPLE_BASENAME = "demo-report"

# A fixed, non-secret salt. The synthetic tenant has no real PII so the
# salt's only role here is to make the redacted principals stable across
# regenerations of the example reports. NEVER reuse this in a live run.
_DOCS_FIXED_SALT = "finops-assess-docs-fixture-salt-v1"

# Stable placeholder written into ``run.input`` of the example report so
# the tempdir leaf name from ``materialise_demo_data`` doesn't pollute
# the committed artefact. Mirrors the redacted shape the JSON reporter
# already emits (``<redacted>/<basename>``).
_DEMO_INPUT_PATH_PLACEHOLDER = "<redacted>/demo"

# Surface labels for the rules reference — keep in sync with the order
# used by the HTML reporter (M365 → Azure → GitHub → ADO).
_SURFACE_LABELS: list[tuple[str, str]] = [
    ("m365", "Microsoft 365"),
    ("azure", "Azure"),
    ("github", "GitHub"),
    ("ado", "Azure DevOps"),
]


def _render_recommendation(template: str) -> str:
    """Collapse whitespace and escape pipes so the cell stays on one row."""
    cleaned = " ".join(template.split())
    return cleaned.replace("|", "\\|")


def render_rules_markdown() -> str:
    """Build the Markdown reference for every rule in ``data/rules/``."""
    rules = load_rules()
    impl_ids = registered_rule_ids()

    by_surface: dict[str, list[object]] = {s: [] for s, _ in _SURFACE_LABELS}
    for rule in rules:
        by_surface.setdefault(rule.surface, []).append(rule)

    out: list[str] = []
    out.append("# Rule reference")
    out.append("")
    out.append(
        "> **This file is auto-generated by `scripts/generate_docs.py`.** "
        "Edit the YAML in `data/rules/` (and its implementation in "
        "`src/finops_assess/rules_impl/`), then re-run the script."
    )
    out.append("")
    out.append(
        f"Counts: **{len(rules)} rules** across "
        f"{sum(1 for _, items in by_surface.items() if items)} surfaces; "
        f"**{sum(1 for r in rules if r.id in impl_ids)} have a registered "
        "implementation**."
    )
    out.append("")
    out.append("Severity values: `info` / `low` / `medium` / `high`.")
    out.append("")

    for surface, label in _SURFACE_LABELS:
        items = by_surface.get(surface, [])
        if not items:
            continue
        out.append(f"## {label} (`{surface}`)")
        out.append("")
        out.append("| Rule ID | Severity | Impl | Inactivity (d) | Summary | Recommendation |")
        out.append("|---------|----------|------|----------------|---------|-----------------|")
        for rule in sorted(items, key=lambda r: r.id):
            impl_marker = "✅" if rule.id in impl_ids else "—"
            inactivity = str(rule.inactivity_days) if rule.inactivity_days is not None else "—"
            summary = rule.summary.replace("|", "\\|")
            recommendation = _render_recommendation(rule.recommendation_template)
            out.append(
                f"| `{rule.id}` | {rule.severity} | {impl_marker} | "
                f"{inactivity} | {summary} | {recommendation} |"
            )
        out.append("")

    # Surface coverage footer — surfaces declared in catalogue without
    # any rule yet. Helps reviewers spot orphaned surfaces.
    declared = {s for s, _ in _SURFACE_LABELS}
    represented = {r.surface for r in rules}
    missing = sorted(declared - represented)
    if missing:
        out.append(f"_Surfaces declared but with no rules yet: {', '.join(missing)}._")
        out.append("")

    return "\n".join(out)


def regenerate_examples(target_dir: Path) -> None:
    """Render `demo-report.{json,html,csv}` into ``target_dir``.

    Uses ``SOURCE_DATE_EPOCH=0`` and a fixed salt so the output is
    byte-stable. Redaction stays on (the synthetic tenant has no real
    PII, but we still want the example to look like a real run).
    """
    target_dir.mkdir(parents=True, exist_ok=True)
    previous_epoch = os.environ.get("SOURCE_DATE_EPOCH")
    os.environ["SOURCE_DATE_EPOCH"] = "0"
    try:
        with tempfile.TemporaryDirectory(prefix="finops-docs-") as tmp:
            demo_input = materialise_demo_data(Path(tmp))
            dataset = collect_from_directory(demo_input)
            catalog = load_catalog()
            personas = load_personas()
            rules = load_rules()
            persona_assignments = assign_personas(dataset, personas)
            findings, summary = run_rules(
                rules=rules,
                catalog=catalog,
                personas=personas,
                persona_assignments=persona_assignments,
                dataset=dataset,
                redact_pii=True,
                salt=_DOCS_FIXED_SALT,
            )
            report = build_report(
                findings=findings,
                summary=summary,
                persona_assignments=persona_assignments,
                input_path=demo_input,
                redact_pii=True,
            )
        # Re-write `run.input` to a stable token so the temp-dir leaf
        # name doesn't pollute the example. Preserves redaction shape.
        report["run"]["input"] = _DEMO_INPUT_PATH_PLACEHOLDER
        write_json_report(report, target_dir / f"{EXAMPLE_BASENAME}.json")
        write_html_report(report, target_dir / f"{EXAMPLE_BASENAME}.html")
        write_csv_report(report, target_dir / f"{EXAMPLE_BASENAME}.csv")
    finally:
        if previous_epoch is None:
            os.environ.pop("SOURCE_DATE_EPOCH", None)
        else:
            os.environ["SOURCE_DATE_EPOCH"] = previous_epoch


def _write_if_changed(path: Path, contents: str) -> bool:
    """Write ``contents`` to ``path`` only if different. Returns True on change."""
    path.parent.mkdir(parents=True, exist_ok=True)
    # Compare as bytes to avoid platform CRLF translation; write with
    # newline="" so docs/rules.md stays byte-identical across OSes.
    encoded = contents.encode("utf-8")
    if path.is_file() and path.read_bytes() == encoded:
        return False
    path.write_text(contents, encoding="utf-8", newline="")
    return True


def _diff_examples(generated_dir: Path, committed_dir: Path) -> list[str]:
    """Return file names that differ (or are missing) between two dirs."""
    diffs: list[str] = []
    for name in sorted(p.name for p in generated_dir.iterdir() if p.is_file()):
        gen = generated_dir / name
        com = committed_dir / name
        if not com.is_file() or not filecmp.cmp(gen, com, shallow=False):
            diffs.append(name)
    if committed_dir.is_dir():
        for name in sorted(p.name for p in committed_dir.iterdir() if p.is_file()):
            if not (generated_dir / name).is_file():
                diffs.append(name)
    return diffs


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Do not write; exit 1 if any artefact differs from the committed copy.",
    )
    args = parser.parse_args(argv)

    rules_md = render_rules_markdown()

    if args.check:
        # Render examples to a temp dir and compare against the committed copy.
        with tempfile.TemporaryDirectory(prefix="finops-docs-check-") as tmp:
            staged = Path(tmp)
            regenerate_examples(staged)
            example_diffs = (
                _diff_examples(staged, EXAMPLES_DIR)
                if EXAMPLES_DIR.is_dir()
                else sorted(p.name for p in staged.iterdir())
            )
        rules_drifted = (
            not DOCS_RULES_PATH.is_file() or DOCS_RULES_PATH.read_text(encoding="utf-8") != rules_md
        )
        if not example_diffs and not rules_drifted:
            print("docs/rules.md and examples/ are up to date.")
            return 0
        print("ERROR: regenerated docs differ from the committed copy.", file=sys.stderr)
        if rules_drifted:
            print(f"  drifted: {DOCS_RULES_PATH.relative_to(REPO_ROOT)}", file=sys.stderr)
        for name in example_diffs:
            print(f"  drifted: examples/{name}", file=sys.stderr)
        print(
            "Run `python scripts/generate_docs.py` and commit the result.",
            file=sys.stderr,
        )
        return 1

    rules_changed = _write_if_changed(DOCS_RULES_PATH, rules_md)
    # Stage examples in a temp dir, then promote — guarantees we never
    # leave the committed examples/ in a half-written state if rendering
    # fails midway through.
    with tempfile.TemporaryDirectory(prefix="finops-docs-write-") as tmp:
        staged = Path(tmp)
        regenerate_examples(staged)
        EXAMPLES_DIR.mkdir(parents=True, exist_ok=True)
        for src in staged.iterdir():
            shutil.copy2(src, EXAMPLES_DIR / src.name)
    print(
        f"Wrote {DOCS_RULES_PATH.relative_to(REPO_ROOT)} ({'changed' if rules_changed else 'unchanged'})"
    )
    print(f"Wrote {EXAMPLES_DIR.relative_to(REPO_ROOT)}/{EXAMPLE_BASENAME}.{{json,html,csv}}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
